<?php

namespace App\Services\CreditLine\Adjust;

use App\Models\CreditLineAdjustment;
use App\Models\CreditLinePayment;
use Carbon\Carbon;
use Illuminate\Support\Facades\DB;

/**
 * Canonical, idempotent enforcer of the credit-line payment generation /
 * supersession invariant.
 *
 * The invariant
 * -------------
 * Every credit_line_payments row is stamped with its owning generation via
 * credit_line_adjustment_id (NULL == the origination generation, i.e. the
 * schedule built at draw time). Generations are chained in adjustment write
 * order (adjusted_at). A row is `cancelled` iff a *later* generation
 * supersedes its slot — concretely, iff its due_date is on/after the
 * effective_date of the adjustment that immediately follows its own
 * generation. Nothing is ever deleted, and no two live (non-cancelled) rows
 * on a line share a due_date. Hence the plan in force on any date D is
 * deterministically the generation whose effective window
 * [effective_date, nextGeneration.effective_date) contains D.
 *
 * What this repairer does (conservative, never destructive):
 *  1. Backfills credit_line_adjustment_id on legacy rows that predate the
 *     stamp (owning generation = latest adjustment written on/before the
 *     row's created_at; none → origination, left NULL).
 *  2. Restores rows that the pre-fix forward-dating bug wrongly cancelled
 *     (cancelled, but their slot is NOT actually superseded, and no surviving
 *     row already covers that due_date) back to `scheduled`.
 *
 * It never deletes, never cancels a live row, never touches paid/partial/late
 * rows, and never creates a duplicate live due_date. A second run over
 * already-consistent data is a strict no-op — including data freshly produced
 * by {@see ReadjustService}, which stamps generations inline.
 *
 * Shared by the {@see \App\Console\Commands\RepairCancelledPreEffectivePayments}
 * command (manual, dry-run by default) and the backfill migration.
 */
class PaymentGenerationRepairer
{
    /**
     * @param  bool $apply  Persist changes (false = dry run: detect only).
     * @return array{restored:int, stamped:int, linesTouched:int}
     */
    public function repair(bool $apply = false): array
    {
        $lineIds = CreditLinePayment::query()
            ->distinct()
            ->pluck('account_credit_line_id');

        $restored = 0;
        $stamped  = 0;
        $linesTouched = 0;

        foreach ($lineIds as $lineId) {
            $result = $this->repairLine((int) $lineId, $apply);
            $restored += $result['restored'];
            $stamped  += $result['stamped'];
            if ($result['restored'] > 0 || $result['stamped'] > 0) {
                $linesTouched++;
            }
        }

        return [
            'restored'     => $restored,
            'stamped'      => $stamped,
            'linesTouched' => $linesTouched,
        ];
    }

    /**
     * @return array{restored:int, stamped:int}
     */
    private function repairLine(int $lineId, bool $apply): array
    {
        /** @var \Illuminate\Support\Collection<int,CreditLineAdjustment> $adjustments */
        $adjustments = CreditLineAdjustment::where('account_credit_line_id', $lineId)
            ->orderBy('adjusted_at')
            ->get()
            ->values();

        $payments = CreditLinePayment::where('account_credit_line_id', $lineId)
            ->orderBy('due_date')
            ->orderBy('id')
            ->get();

        // ── 1. Backfill missing generation stamps ──────────────────────────
        // A NULL stamp on a row created on/after an adjustment means the row
        // was generated by that adjustment but predates inline stamping.
        // Owning generation = the latest adjustment whose adjusted_at is on or
        // before the row's created_at. None → origination (stays NULL).
        $stampPlan = []; // payment id => adjustment id
        foreach ($payments as $p) {
            if ($p->credit_line_adjustment_id !== null || !$p->created_at) {
                continue;
            }
            $owner = null;
            foreach ($adjustments as $a) {
                if ($a->adjusted_at && $a->adjusted_at->lte($p->created_at)) {
                    $owner = $a;
                } else {
                    break; // adjustments are adjusted_at-ascending
                }
            }
            if ($owner !== null) {
                $stampPlan[$p->id] = $owner->id;
                // Reflect the resolved generation locally so the supersession
                // pass below sees the corrected owner.
                $p->credit_line_adjustment_id = $owner->id;
            }
        }

        // ── 2. Restore wrongly-cancelled, non-superseded rows ──────────────
        // The adjustment that supersedes a generation is the one written
        // immediately after it (origination's = the first adjustment).
        $adjIndexById = [];
        foreach ($adjustments as $i => $a) {
            $adjIndexById[$a->id] = $i;
        }

        $supersedingFor = function (?int $generationId) use ($adjustments, $adjIndexById): ?CreditLineAdjustment {
            $ownerIdx = $generationId === null ? -1 : ($adjIndexById[$generationId] ?? null);
            if ($ownerIdx === null) {
                return null; // unknown generation: leave the row untouched
            }
            return $adjustments[$ownerIdx + 1] ?? null;
        };

        // Due dates already carrying a live obligation — never double-bill.
        $coveredDueDates = [];
        foreach ($payments as $p) {
            if ($p->status !== CreditLinePayment::STATUS_CANCELLED) {
                $coveredDueDates[Carbon::parse($p->due_date)->toDateString()] = true;
            }
        }

        $restorePlan = []; // payment ids to set scheduled
        foreach ($payments as $p) {
            if ($p->status !== CreditLinePayment::STATUS_CANCELLED) {
                continue;
            }
            $superseding = $supersedingFor($p->credit_line_adjustment_id);

            // Rightfully cancelled iff a later generation supersedes its slot.
            $rightfullyCancelled = $superseding !== null
                && Carbon::parse($p->due_date)->gte(Carbon::parse($superseding->effective_date));
            if ($rightfullyCancelled) {
                continue;
            }

            $dueKey = Carbon::parse($p->due_date)->toDateString();
            if (isset($coveredDueDates[$dueKey])) {
                continue; // a surviving row already covers this date
            }

            $restorePlan[] = $p->id;
            $coveredDueDates[$dueKey] = true; // prevent restoring a duplicate
        }

        if ($apply && (!empty($stampPlan) || !empty($restorePlan))) {
            DB::transaction(function () use ($stampPlan, $restorePlan) {
                // One bulk update per generation.
                foreach ($this->groupByValue($stampPlan) as $adjId => $ids) {
                    CreditLinePayment::whereIn('id', $ids)
                        ->update(['credit_line_adjustment_id' => $adjId]);
                }
                if (!empty($restorePlan)) {
                    CreditLinePayment::whereIn('id', $restorePlan)
                        ->update(['status' => CreditLinePayment::STATUS_SCHEDULED]);
                }
            });
        }

        return [
            'restored' => count($restorePlan),
            'stamped'  => count($stampPlan),
        ];
    }

    /**
     * Invert [paymentId => adjustmentId] into [adjustmentId => [paymentIds]]
     * so each generation is stamped in a single bulk update.
     *
     * @param  array<int,int> $stampPlan
     * @return array<int,array<int,int>>
     */
    private function groupByValue(array $stampPlan): array
    {
        $grouped = [];
        foreach ($stampPlan as $paymentId => $adjId) {
            $grouped[$adjId][] = $paymentId;
        }
        return $grouped;
    }
}
