<?php

namespace App\Http\Controllers\WebV1;

use App\Http\Controllers\AppBaseController;
use App\Http\Requests\CancelCreditLineRequest;
use App\Http\Requests\CreateAccountCreditLineRequest;
use App\Http\Requests\ReadjustCreditLineRequest;
use App\Http\Requests\RegisterCreditLinePaymentRequest;
use App\Http\Requests\RepayCreditLineRequest;
use App\Http\Requests\UpdateAccountCreditLineRequest;
use App\Models\AccountCreditLine;
use App\Models\AccountCreditLineExt;
use App\Models\AccountExt;
use App\Models\CreditLinePayment;
use App\Models\TransactionExt;
use App\Models\UserExt;
use App\Services\CreditLine\Adjust\AdjustmentHistoryBuilder;
use App\Services\CreditLine\Adjust\ReadjustService;
use App\Services\CreditLine\Adjust\ScheduleSnapshotBuilder;
use App\Services\CreditLine\Cancel\CancelService;
use App\Services\CreditLine\Draw\DrawService;
use App\Services\CreditLine\Exceptions\CancelNotAllowedException;
use App\Services\CreditLine\Exceptions\NoChangeException;
use App\Services\CreditLine\Exceptions\OverBorrowException;
use App\Services\CreditLine\Repay\RepayService;
use App\Services\CreditLine\Reporting\LoansSummaryBuilder;
use App\Services\CreditLine\Reporting\TrajectoryBuilder;
use App\Services\CreditLine\Reverse\Exceptions\AlreadyReversedException;
use App\Services\CreditLine\Reverse\ReverseService;
use App\Services\CreditLine\Simulation\PaymentSimulator;
use App\Services\CreditLine\Support\OutstandingCalculator;
use Carbon\Carbon;
use Flash;
use Illuminate\Http\Request;
use InvalidArgumentException;

class AccountCreditLineControllerExt extends AppBaseController
{
    public function __construct(
        private readonly DrawService $drawService,
        private readonly RepayService $repayService,
        private readonly ReadjustService $readjustService,
        private readonly CancelService $cancelService,
        private readonly AdjustmentHistoryBuilder $historyBuilder,
        private readonly ReverseService $reverseService,
    ) {}

    /**
     * Admin gate for read-only credit-line endpoints.
     *
     * Wave-2 review (2026-05-14) flagged that index/show/create/edit had no
     * is_admin() check — only `simulator()` did. A non-admin authenticated
     * user could GET other accounts' credit-line data. Mirror the simulator
     * gate pattern here as a shared helper.
     */
    private function ensureAdmin(): void
    {
        if (!auth()->user()?->is_admin()) {
            abort(403);
        }
    }

    public function index($accountId, Request $request)
    {
        $this->ensureAdmin();
        $account = AccountExt::findOrFail($accountId);
        $this->authorize('viewAny', [AccountCreditLineExt::class, $account]);

        $nickname = trim((string) $request->query('nickname', ''));

        $lines = AccountCreditLine::where('account_id', $account->id)
            ->when($nickname !== '', fn ($q) => $q->where('nickname', 'like', '%' . $nickname . '%'))
            ->orderByDesc('id')
            ->get();

        return view('account_credit_lines.index')
            ->with('account', $account)
            ->with('lines', $lines)
            ->with('nickname', $nickname);
    }

    /**
     * Global (cross-account) credit-line listing. Admin-only.
     */
    public function globalIndex(Request $request)
    {
        $this->ensureAdmin();

        $nickname = trim((string) $request->query('nickname', ''));

        $lines = AccountCreditLine::with('account')
            ->when($nickname !== '', fn ($q) => $q->where('nickname', 'like', '%' . $nickname . '%'))
            ->orderByRaw("FIELD(status, 'active') DESC")
            ->orderByDesc('id')
            ->get();

        return view('account_credit_lines.global_index')
            ->with('lines', $lines)
            ->with('nickname', $nickname);
    }

    /**
     * Global (cross-account) open/late receivables listing. Admin-only.
     *
     * Shows every schedule row that is still open (scheduled / partial /
     * late) so the operator can see — and reconcile — the outstanding
     * backlog, including rows generated by backdated draws.
     */
    public function globalPayments(Request $request)
    {
        $this->ensureAdmin();

        $openStatuses = [
            CreditLinePayment::STATUS_SCHEDULED,
            CreditLinePayment::STATUS_PARTIAL,
            CreditLinePayment::STATUS_LATE,
        ];

        $allStatuses = [
            CreditLinePayment::STATUS_SCHEDULED,
            CreditLinePayment::STATUS_PARTIAL,
            CreditLinePayment::STATUS_LATE,
            CreditLinePayment::STATUS_PAID,
            CreditLinePayment::STATUS_CANCELLED,
        ];

        // 'open' (default) keeps the original open-receivables view; a
        // specific status narrows to it; 'all' shows everything.
        $status    = $request->query('status', 'open');
        $accountId = $request->query('account_id');
        $fundId    = $request->query('fund_id');
        $nickname  = trim((string) $request->query('nickname', ''));

        $query = CreditLinePayment::with(['creditLine.account.fund'])
            ->orderBy('due_date');

        if ($status === 'open') {
            $query->whereIn('status', $openStatuses);
        } elseif ($status !== 'all') {
            $query->where('status', $status);
        }

        if ($nickname !== '') {
            $query->whereHas('creditLine', fn ($q) => $q->where('nickname', 'like', '%' . $nickname . '%'));
        }
        if ($accountId) {
            $query->whereHas('creditLine', fn ($q) => $q->where('account_id', $accountId));
        }
        if ($fundId) {
            $query->whereHas('creditLine.account', fn ($q) => $q->where('fund_id', $fundId));
        }

        // Filter option lists: only accounts/funds that actually have
        // credit lines, so the dropdowns stay scoped to relevant choices.
        $accounts = AccountExt::whereIn('id', AccountCreditLine::query()->select('account_id'))
            ->with('fund')
            ->orderBy('nickname')
            ->get();
        $funds = $accounts->pluck('fund')
            ->filter()
            ->unique('id')
            ->sortBy('name')
            ->values();

        return view('account_credit_lines.global_payments')
            ->with('payments', $query->get())
            ->with('status', $status)
            ->with('statusOptions', $allStatuses)
            ->with('accounts', $accounts)
            ->with('funds', $funds)
            ->with('accountId', $accountId)
            ->with('fundId', $fundId)
            ->with('nickname', $nickname)
            ->with('today', Carbon::today());
    }

    public function create($accountId, OutstandingCalculator $calculator)
    {
        $this->ensureAdmin();
        $account = AccountExt::findOrFail($accountId);
        $this->authorize('create', [AccountCreditLineExt::class, $account]);

        $available = $calculator->availableToBorrow($account, Carbon::today());

        return view('account_credit_lines.create')
            ->with('account', $account)
            ->with('available', round($available, 4));
    }

    /**
     * JSON: available-to-borrow shares for an account as of a given date.
     *
     * Backs the create form's live "available shares" readout — when the
     * origination date changes (e.g. a backdated draw) the borrow cap is
     * recomputed against the OWN balance as of that date.
     */
    public function availableShares($accountId, Request $request, OutstandingCalculator $calculator)
    {
        $this->ensureAdmin();
        $account = AccountExt::findOrFail($accountId);
        $this->authorize('create', [AccountCreditLineExt::class, $account]);

        $asOf = $request->query('as_of');
        try {
            $date = !empty($asOf) ? Carbon::parse($asOf) : Carbon::today();
        } catch (\Throwable $e) {
            $date = Carbon::today();
        }
        if ($date->gt(Carbon::today())) {
            $date = Carbon::today();
        }

        return response()->json([
            'as_of'     => $date->toDateString(),
            'available' => round($calculator->availableToBorrow($account, $date), 4),
        ]);
    }

    /**
     * Global create form — opened from the cross-account /credit-lines
     * listing with no account in context. The account is chosen in the
     * form; store() reads account_id from the request body either way.
     */
    public function globalCreate()
    {
        $this->ensureAdmin();

        $accounts = AccountExt::with('user')
            ->orderBy('nickname')
            ->get(['id', 'nickname', 'code', 'fund_id', 'user_id']);

        return view('account_credit_lines.create')
            ->with('account', null)
            ->with('accounts', $accounts)
            ->with('fundMap', \App\Models\FundExt::fundMap())
            ->with('available', 0.0);
    }

    /**
     * JSON: available-to-borrow shares for the account chosen in the global
     * create form. Mirrors availableShares() but takes the account from a
     * query param instead of the route (no account in the global URL).
     */
    public function globalAvailableShares(Request $request, OutstandingCalculator $calculator)
    {
        $this->ensureAdmin();
        $account = AccountExt::findOrFail($request->query('account'));
        $this->authorize('create', [AccountCreditLineExt::class, $account]);

        $asOf = $request->query('as_of');
        try {
            $date = !empty($asOf) ? Carbon::parse($asOf) : Carbon::today();
        } catch (\Throwable $e) {
            $date = Carbon::today();
        }
        if ($date->gt(Carbon::today())) {
            $date = Carbon::today();
        }

        return response()->json([
            'as_of'     => $date->toDateString(),
            'available' => round($calculator->availableToBorrow($account, $date), 4),
        ]);
    }

    public function store(CreateAccountCreditLineRequest $request)
    {
        $data = $request->validated();
        $account = AccountExt::findOrFail($data['account_id']);
        $this->authorize('create', [AccountCreditLineExt::class, $account]);

        $originationDate = !empty($data['origination_date'])
            ? Carbon::parse($data['origination_date'])
            : null;
        $isBackdated = $originationDate !== null
            && $originationDate->lt(Carbon::today());

        try {
            $line = $this->drawService->open(
                $account,
                (float) $data['principal_shares'],
                (int) $data['term_months'],
                $data['payment_frequency'],
                $data['descr'] ?? null,
                $originationDate,
                $data['nickname']
            );
        } catch (OverBorrowException $e) {
            Flash::error($e->getMessage());
            return redirect()->back()->withInput();
        } catch (InvalidArgumentException $e) {
            // OutstandingCalculator's backdate guard: the chosen date predates
            // an existing open BOR balance row for this account. FF cannot
            // splice a draw before already-recorded borrow history.
            Flash::error(
                'Cannot backdate to ' . $originationDate?->toDateString()
                . ': the account already has recorded borrow activity on or after that date. '
                . 'Choose a later origination date. (' . $e->getMessage() . ')'
            );
            return redirect()->back()->withInput();
        }

        if ($isBackdated) {
            $lateCount = $line->payments()
                ->where('status', \App\Models\CreditLinePayment::STATUS_LATE)
                ->count();
            Flash::warning(
                'Credit line #' . $line->id . ' backdated to ' . $originationDate->toDateString()
                . '. ' . $lateCount . ' payment row(s) are already past due and flagged late. '
                . 'FamilyFund will not settle them — register any payments that already '
                . 'happened from the schedule below.'
            );
        }

        Flash::success('Credit line #' . $line->id . ' opened.');

        return redirect(route('credit_lines.show', ['line' => $line->id]));
    }

    public function show(
        $id,
        TrajectoryBuilder $trajectoryBuilder,
        LoansSummaryBuilder $loansSummaryBuilder,
        ScheduleSnapshotBuilder $snapshotBuilder
    ) {
        $this->ensureAdmin();
        $line = AccountCreditLineExt::findOrFail($id);
        $this->authorize('view', $line);
        $account = $line->account()->first();
        $history = $this->historyBuilder->build($line);
        $schedule = $line->payments()->orderBy('due_date')->get();
        $trajectory = $trajectoryBuilder->build($line);
        $loansSummary = $account ? $loansSummaryBuilder->forAccount($account) : [];

        // Build per-adjustment schedule snapshots so the timeline can render
        // an inline "View schedule at this point" modal for each adjustment
        // (Phase 4, deferred from Phase 3).
        $scheduleSnapshots = [];
        foreach ($history as $entry) {
            if (($entry['kind'] ?? null) !== 'adjustment') {
                continue;
            }
            $adjId = $entry['data']['id'] ?? null;
            $adjAt = $entry['data']['adjusted_at'] ?? $entry['date'] ?? null;
            if ($adjId && $adjAt) {
                $scheduleSnapshots[$adjId] = $snapshotBuilder->snapshotAt($line, $adjAt);
            }
        }

        // $-value of each schedule row at the share price of its due date
        // ("price of the day"). Only for rows whose due date has already
        // passed — a future row's price isn't known yet. Cached per distinct
        // date so a 480-row schedule doesn't fan out one query per row.
        $today = Carbon::today();
        $priceCache = [];
        $scheduleDollars = [];
        foreach ($schedule as $scheduleRow) {
            $due = Carbon::parse($scheduleRow->due_date);
            if ($due->gt($today)) {
                continue;
            }
            $key = $due->toDateString();
            if (!array_key_exists($key, $priceCache)) {
                try {
                    $priceCache[$key] = (float) ($account?->shareValueAsOf($key) ?? 0);
                } catch (\Throwable $e) {
                    $priceCache[$key] = 0.0;
                }
            }
            if ($priceCache[$key] > 0) {
                $scheduleDollars[$scheduleRow->id] = $scheduleRow->shares_due * $priceCache[$key];
            }
        }

        return view('account_credit_lines.show')
            ->with('line', $line)
            ->with('account', $account)
            ->with('schedule', $schedule)
            ->with('scheduleDollars', $scheduleDollars)
            ->with('history', $history)
            ->with('trajectory', $trajectory)
            ->with('loansSummary', $loansSummary)
            ->with('scheduleSnapshots', $scheduleSnapshots);
    }

    /**
     * Dedicated admin-actions page (UC: repay / readjust / cancel).
     *
     * The show page previously embedded these as inline forms; moved to a
     * standalone page reached via a link at the top of show — same pattern
     * as the per-row register-payment page.
     */
    public function actions($id)
    {
        $this->ensureAdmin();
        $line = AccountCreditLineExt::findOrFail($id);
        $this->authorize('process', $line);
        $account = $line->account()->with('fund')->first();
        $schedule = $line->payments()->orderBy('due_date')->get();

        return view('account_credit_lines.actions')
            ->with('line', $line)
            ->with('account', $account)
            ->with('schedule', $schedule);
    }

    public function edit($id)
    {
        $this->ensureAdmin();
        $line = AccountCreditLineExt::findOrFail($id);
        $this->authorize('update', $line);
        $account = $line->account()->with('fund')->first();

        return view('account_credit_lines.edit')
            ->with('line', $line)
            ->with('account', $account);
    }

    /**
     * UC-20: persist notification-settings edits.
     *
     * Only the 7 reminder / email columns are mutable here. Principal, term,
     * status, etc. are protected — use Readjust / Cancel for those.
     */
    public function update(UpdateAccountCreditLineRequest $request, $id)
    {
        $line = AccountCreditLineExt::findOrFail($id);
        $this->authorize('update', $line);

        $line->fill($request->validated())->save();

        Flash::success('Notification settings updated for credit line #' . $line->id . '.');

        return redirect(route('credit_lines.show', ['line' => $line->id]));
    }

    public function repay(RepayCreditLineRequest $request)
    {
        $data = $request->validated();
        $line = AccountCreditLineExt::findOrFail($data['account_credit_line_id']);
        $this->authorize('process', $line);
        $date = isset($data['date']) ? Carbon::parse($data['date']) : null;

        try {
            $tran = $this->repayService->repay($line, (float) $data['shares'], $date);
        } catch (InvalidArgumentException $e) {
            Flash::error($e->getMessage());
            return redirect(route('credit_lines.show', ['line' => $line->id]));
        }

        Flash::success('Repayment recorded (txn #' . $tran->id . ').');

        return redirect(route('credit_lines.show', ['line' => $line->id]));
    }

    /**
     * Dedicated register-payment page — reachable from the cross-account
     * Receivables list (and anywhere a single schedule row needs settling).
     * Renders the same form the show-page modal posts; submission still
     * goes through registerPayment() below.
     */
    public function registerPaymentForm($lineId, $paymentId)
    {
        $this->ensureAdmin();
        $line = AccountCreditLineExt::findOrFail($lineId);
        $this->authorize('process', $line);

        $row = CreditLinePayment::where('id', $paymentId)
            ->where('account_credit_line_id', $line->id)
            ->firstOrFail();

        $account = $line->account()->with('fund')->first();

        $shareValue = 0.0;
        try {
            $shareValue = (float) $account?->shareValueAsOf(Carbon::today()->toDateString());
        } catch (\Throwable $e) {
            // share price unavailable — page still renders, $ amount hidden
        }

        return view('account_credit_lines.register_payment')
            ->with('line', $line)
            ->with('row', $row)
            ->with('account', $account)
            ->with('shareValue', $shareValue);
    }

    /**
     * Per-row manual payment registration.
     *
     * Reconciles a single schedule installment that an external system
     * settled. The amount is admin-editable (defaults to the row's
     * shares_due in the form) and the date is the real settlement date.
     */
    public function registerPayment(RegisterCreditLinePaymentRequest $request, $lineId, $paymentId)
    {
        $line = AccountCreditLineExt::findOrFail($lineId);
        $this->authorize('process', $line);

        $row = CreditLinePayment::where('id', $paymentId)
            ->where('account_credit_line_id', $line->id)
            ->firstOrFail();

        $data = $request->validated();
        $date = !empty($data['date']) ? Carbon::parse($data['date']) : null;

        try {
            $tran = $this->repayService->repayRow($row, (float) $data['shares'], $date);
        } catch (InvalidArgumentException $e) {
            Flash::error($e->getMessage());
            return redirect(route('credit_lines.show', ['line' => $line->id]));
        }

        Flash::success(
            'Payment registered on schedule row #' . $row->id
            . ' (txn #' . $tran->id . ').'
        );

        return redirect(route('credit_lines.show', ['line' => $line->id]));
    }

    /**
     * Reverse a registered payment on a schedule row (the "Delete" / "Edit"
     * controls on the schedule and Receivables lists).
     *
     * Reverses the row's REP transaction via ReverseService — which re-opens
     * every row that transaction had satisfied (a cascaded over-payment can
     * touch several) and restores the line's outstanding. With `then=edit`
     * the admin is sent straight to the register form to re-enter correct
     * values; otherwise we return to the page they came from.
     */
    public function reversePayment(Request $request, $lineId, $paymentId)
    {
        $this->ensureAdmin();
        $line = AccountCreditLineExt::findOrFail($lineId);
        $this->authorize('process', $line);

        $row = CreditLinePayment::where('id', $paymentId)
            ->where('account_credit_line_id', $line->id)
            ->firstOrFail();

        if (!$row->paid_transaction_id) {
            Flash::error('Schedule row #' . $row->id . ' has no registered payment to reverse.');
            return redirect()->back();
        }

        $tran = TransactionExt::findOrFail($row->paid_transaction_id);

        /** @var UserExt|null $admin */
        $admin = auth()->user();
        if ($admin && !$admin instanceof UserExt) {
            $admin = UserExt::find($admin->id);
        }

        $isEdit = $request->input('then') === 'edit';
        $reason = trim((string) $request->input('reason'));
        if ($reason === '') {
            $reason = $isEdit
                ? 'Editing mis-registered payment on schedule row #' . $row->id . ' (reverse + re-register).'
                : 'Deleting mis-registered payment on schedule row #' . $row->id . '.';
        }

        try {
            $reversal = $this->reverseService->reverse($tran, $admin, $reason);
        } catch (AlreadyReversedException $e) {
            Flash::error($e->getMessage());
            return redirect()->back();
        }

        Flash::success(
            'Payment on schedule row #' . $row->id
            . ' reversed (txn #' . $tran->id . ', reversal #' . $reversal->id . ').'
        );

        if ($isEdit) {
            return redirect(route('credit_lines.payments.register_form', [
                'line'    => $line->id,
                'payment' => $row->id,
            ]));
        }

        return redirect()->back();
    }

    public function readjust(ReadjustCreditLineRequest $request)
    {
        $data = $request->validated();
        $line = AccountCreditLineExt::findOrFail($data['account_credit_line_id']);
        $this->authorize('process', $line);

        /** @var UserExt|null $admin */
        $admin = auth()->user();
        if ($admin && !$admin instanceof UserExt) {
            $admin = UserExt::find($admin->id);
        }

        try {
            $adj = $this->readjustService->readjust(
                $line,
                isset($data['new_term_months']) ? (int) $data['new_term_months'] : null,
                $data['new_payment_frequency'] ?? null,
                $admin,
                $data['reason'] ?? null,
                !empty($data['effective_date']) ? Carbon::parse($data['effective_date']) : null
            );
        } catch (NoChangeException $e) {
            Flash::error($e->getMessage());
            return redirect()->back()->withInput();
        }

        Flash::success('Credit line readjusted (adjustment #' . $adj->id . ').');

        return redirect(route('credit_lines.show', ['line' => $line->id]));
    }

    public function cancel(CancelCreditLineRequest $request)
    {
        $data = $request->validated();
        $line = AccountCreditLineExt::findOrFail($data['account_credit_line_id']);
        $this->authorize('delete', $line);

        try {
            $this->cancelService->cancel($line);
        } catch (CancelNotAllowedException $e) {
            Flash::error($e->getMessage());
            return redirect(route('credit_lines.show', ['line' => $line->id]));
        }

        Flash::success('Credit line cancelled.');

        return redirect(route('credit_lines.show', ['line' => $line->id]));
    }

    /**
     * Phase 9: payment simulator — read-only "what if" projection.
     *
     * Admin-gated. Renders the simulator view. If a positive
     * `monthly_payment_usd` is supplied via the query string, runs the
     * three-scenario simulation (conservative / expected / aggressive)
     * and passes the results to the view; otherwise renders the form
     * with no results.
     */
    public function simulator($id, Request $request, PaymentSimulator $simulator)
    {
        $this->ensureAdmin();

        $line = AccountCreditLineExt::findOrFail($id);
        $this->authorize('process', $line);
        $account = $line->account()->first();

        $currentShareValue = null;
        try {
            $currentShareValue = $account
                ? (float) $account->shareValueAsOf(Carbon::today()->toDateString())
                : null;
        } catch (\Throwable $e) {
            $currentShareValue = null;
        }

        $mode = $request->query('mode', 'payment');
        if (!in_array($mode, ['payment', 'time'], true)) {
            $mode = 'payment';
        }

        $monthlyPaymentUsd = $request->query('monthly_payment_usd');
        $targetMonths = $request->query('target_months');
        $results = [];
        $solvedPayments = [];
        $error = null;

        if ($mode === 'time') {
            if ($targetMonths !== null && $targetMonths !== '') {
                $targetMonths = (int) $targetMonths;
                if ($targetMonths < 1 || $targetMonths > 600) {
                    $error = 'target_months must be between 1 and 600';
                } else {
                    try {
                        $all = $simulator->solveForPaymentAllScenarios($line, $targetMonths);
                        foreach ($all as $k => $row) {
                            $results[$k] = $row['result'];
                            $solvedPayments[$k] = $row['payment'];
                        }
                    } catch (InvalidArgumentException $e) {
                        $error = $e->getMessage();
                    }
                }
            } else {
                $targetMonths = null;
            }
        } else {
            if ($monthlyPaymentUsd !== null && $monthlyPaymentUsd !== '') {
                $monthlyPaymentUsd = (float) $monthlyPaymentUsd;
                try {
                    $results = $simulator->simulateAllScenarios($line, $monthlyPaymentUsd);
                } catch (InvalidArgumentException $e) {
                    $error = $e->getMessage();
                }
            } else {
                $monthlyPaymentUsd = null;
            }
        }

        return view('account_credit_lines.simulator')
            ->with('line', $line)
            ->with('account', $account)
            ->with('currentShareValue', $currentShareValue)
            ->with('mode', $mode)
            ->with('monthlyPaymentUsd', is_numeric($monthlyPaymentUsd) ? (float) $monthlyPaymentUsd : null)
            ->with('targetMonths', is_numeric($targetMonths) ? (int) $targetMonths : null)
            ->with('results', $results)
            ->with('solvedPayments', $solvedPayments)
            ->with('simError', $error);
    }
}
