<!-- Type Field -->
{!! Form::hidden('type', $transaction['type']) !!}
{!! Form::hidden('status', $transaction['status']) !!}
{!! Form::hidden('value', $transaction['value']) !!}
{!! Form::hidden('flags', $transaction['flags']) !!}
{!! Form::hidden('timestamp', $transaction['timestamp']) !!}
{!! Form::hidden('account_id', $transaction['account_id']) !!}
{!! Form::hidden('shares', $transaction['shares']) !!}
{!! Form::hidden('descr', $transaction['descr']) !!}
