services:
  mariadb:
    environment:
      - ALLOW_EMPTY_PASSWORD=no
      - MARIADB_USER=famfun_dev
      - MARIADB_DATABASE=familyfund_dev
      - MARIADB_PASSWORD=${FF_DB_USER_PASSWORD:-changeme}
      - MARIADB_ROOT_PASSWORD=${FF_DB_ROOT_PASSWORD:-changeme}
    ports:
      - 3306:3306
    volumes:
      - ./datadir_dev:/var/lib/mysql

  familyfund:
    environment:
      - DB_DATABASE=familyfund_dev
      - DB_USERNAME=root
      - DB_PASSWORD=${FF_DB_PASSWORD:-changeme}
      - APP_ENV=dev
    ports:
      - 3001:8000
