/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

DROP TABLE IF EXISTS `accounts`;
DROP TABLE IF EXISTS `transactions`;
DROP TABLE IF EXISTS `account_balances`;
DROP TABLE IF EXISTS `account_matching_rules`;
DROP TABLE IF EXISTS `account_reports`;
DROP TABLE IF EXISTS `accounts`;
DROP TABLE IF EXISTS `asset_change_logs`;
DROP TABLE IF EXISTS `asset_prices`;
DROP TABLE IF EXISTS `assets`;
DROP TABLE IF EXISTS `failed_jobs`;
DROP TABLE IF EXISTS `funds`;
DROP TABLE IF EXISTS `fund_reports`;
DROP TABLE IF EXISTS `matching_rules`;
DROP TABLE IF EXISTS `migrations`;
DROP TABLE IF EXISTS `password_resets`;
DROP TABLE IF EXISTS `personal_access_tokens`;
DROP TABLE IF EXISTS `portfolio_assets`;
DROP TABLE IF EXISTS `portfolios`;
DROP TABLE IF EXISTS `transactions`;
DROP TABLE IF EXISTS `transaction_matchings`;

/*!40103 SET TIME_ZONE=@OLD_TIME_ZONE */;
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;

