<?php
namespace Tests\Feature;

use App\Models\AccountExt;
use Illuminate\Foundation\Testing\WithoutMiddleware;
use Illuminate\Foundation\Testing\DatabaseTransactions;
use PHPUnit\Framework\Attributes\DataProvider;
use Tests\TestCase;
use Tests\ApiTestTrait;
use Tests\DataFactory;

class PerformanceTraitTests extends TestCase
{
    use ApiTestTrait, WithoutMiddleware, DatabaseTransactions;


    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    #[DataProvider('twrDataProvider')]
    public function testTWR($periods, $expected)
    {
        $perf = AccountExt::calculateTWR($periods) * 100.0;
        $this->assertEquals($expected, $perf);
    }

    public static function twrDataProvider()
    {
        // $startValue, $endValue, $cashFlow
        return [
            [[[1000, 1200, 0]], 20],
            [[[1000, 1200, 200]], 0],
            [[[1000, 1400, 200]], 20],
            [[[1000, 1200, 0],   [1200, 1400, 0]], 40],
            [[[1000, 1200, 0],   [1200, 1400, 200]], 20],
            [[[ 800, 1000, 200], [1000, 1200, 0]], 20],
        ];
    }


}
