<?php namespace Tests\APIs;

use App\Http\Controllers\Traits\ScheduledJobTrait;
use App\Models\FundReportExt;
use App\Models\ScheduledJob;
use App\Models\ScheduledJobExt;
use App\Models\ScheduleExt;
use App\Models\TransactionExt;
use App\Repositories\ScheduledJobRepository;
use Illuminate\Foundation\Testing\WithoutMiddleware;
use Illuminate\Foundation\Testing\DatabaseTransactions;
use Illuminate\Support\Carbon;
use Log;
use Tests\DataFactory;
use Tests\TestCase;
use Tests\ApiTestTrait;
use Exception;
use Mockery\MockInterface;

class ScheduledTransactionTest extends TestCase
{
    use ApiTestTrait, WithoutMiddleware, DatabaseTransactions, ScheduledJobTrait;

    private DataFactory $factory;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->factory = $factory = new DataFactory();
        $factory->createFund(1000, 1000, '2021-01-01');
        $factory->createUser();
        $factory->verbose = $this->verbose;
        $this->setupHandlers();
    }

    /**
     * @test
     */
    public function test_schedule_transaction()
    {
        $this->debug("\n\n\n");
        /** @var DataFactory $factory */
        $factory = $this->factory;
        $date = Carbon::today()->subDays(7)->previous(Carbon::MONDAY);
        $origDate = $date->copy();
        $value = 100;
        $dow = 1;

        /* @var ScheduledJobExt $job */
        /* @var TransactionExt $stran */
        list ($schedule, $job, $stran) = $factory->createScheduledTransaction(
            ScheduleExt::TYPE_DAY_OF_WEEK, $dow, $date, $value);

        $expectedCount = 1; // 1 for monday
        $tran = $this->_testScheduledJob($date, ScheduledJobExt::ENTITY_TRANSACTION, $job, $expectedCount);

        // type, status, value, shares, timestamp, account_id, descr, flags, scheduled_job_id,
        $this->assertEquals($origDate->toDateString(), $tran->timestamp->toDateString());
        $this->assertEquals($value, $tran->value);
        $this->assertEquals(TransactionExt::TYPE_PURCHASE, $tran->type);
        $this->assertEquals(TransactionExt::STATUS_CLEARED, $tran->status);
        $this->assertGreaterThan(0, $tran->shares);
        $this->assertEquals($stran->account_id, $tran->account_id);
        $this->assertEquals($stran->descr, $tran->descr);
        $this->assertEquals($stran->flags, $tran->flags);
    }

    protected function createFundReport(array $input) {
        $fundReport = FundReportExt::create($input);
        $this->validateReportEmails($fundReport);
        $fundReport->save();
        return $fundReport;
    }

    // test schedule report
    public function test_sched_fund_report() {
        $this->debug("\n\n\n");
        $factory = $this->factory;
        $date = Carbon::today()->subDays(7)->previous(Carbon::SUNDAY);
        $origDate = $date->copy();

        // create prices to trick "missing data for fund report"
        $asset = $factory->createAsset('FFIB');
        for ($i = 0; $i < 7; $i++) {
            $tomorrow = $date->copy()->addDay();
            $factory->createAssetPrice($asset, 10.2, $date, $tomorrow);
            $date = $tomorrow;
        }
        $date = $origDate->copy();

        /* @var ScheduledJobExt $job */
        /* @var FundReportExt $srep */
        list ($schedule, $job, $srep) = $factory->createScheduledFundReport(ScheduleExt::TYPE_DAY_OF_WEEK,
            2, $factory->fund, FundReportExt::TYPE_ADMIN, $date);

        $expectedCount = 2; // monday (in delay of prev week) and tue
        $rep = $this->_testScheduledJob($date, ScheduledJobExt::ENTITY_FUND_REPORT, $job, $expectedCount);

        $this->debug('job: ' . json_encode($job->toArray()));

        // type, as_of,
        $this->assertEquals($origDate->next(Carbon::TUESDAY)->toDateString(), $rep->as_of->toDateString());
        $this->assertEquals($srep->type, $rep->type);
    }

    private function _testScheduledJob(Carbon $date, $entityDescrFilter, ScheduledJobExt $job, $expected=1): mixed
    {
        $all = [];
        $this->debug("******* test sched fund report ********");
        for ($i = 0; $i < 7; $i++) {
            $this->debug('At date: ' . $date->toDateString() . ', dow: ' . $date->dayOfWeek);
            $all[] = list($ret, $errors) = $this->scheduleDueJobs($date, $entityDescrFilter);
            $this->debug('Scheduled jobs: ' . json_encode($ret));
            $date->addDay();
        }
        // count all scheduled jobs by this schedule id
        $found = null;
        $count = 0;
        foreach ($all as list ($ret, $errors)) {
            foreach ($ret as $obj) {
                if ($obj->scheduled_job_id == $job->id) {
                    $count++;
                    $found = $obj;
                    $this->debug('Scheduled job: ' . json_encode($found->toArray()));
                }
            }
        }
        $this->assertEquals($expected, $count, 'One scheduled job');
        $this->debug('job: ' . json_encode($job->toArray()));

        $this->assertEquals($job->id, $found?->scheduled_job_id);
        return $found;
    }
}
