### GET prod account
GET http://REDACTED_LAN_HOST:3001/api/trade_portfolios/
Accept: application/json

### GET prod account
GET http://REDACTED_LAN_HOST:3001/api/trade_portfolios/U0000012
Accept: application/json

### GET dev account
GET http://localhost:3000/api/trade_portfolios/acct2
Accept: application/json

### GET dev account
GET http://localhost:3000/api/trade_portfolios/
Accept: application/json

### GET fail account
GET http://localhost:3000/api/trade_portfolios/AAA
Accept: application/json

### GET share price
GET http://localhost:3000/api/accounts/1/share_value_as_of/2022-08-06
Accept: application/json

### GET share price
GET http://localhost:3000/api/fund_reports/1
Accept: application/json

### Post bulk update
POST http://REDACTED_LAN_HOST:3001/api/portfolio_assets_bulk_update
Content-Type: application/json

{"source":"DWGIB","symbols":[
{"name":"CASH","position":2034.34,"type":"CSH"},
{"name":"SPXL","position":"14.00000000","type":"STK"},
{"name":"SOXL","position":"36.00000000","type":"STK"},
{"name":"TECL","position":"16.00000000","type":"STK"},
{"name":"IAU","position":"39.00000000","type":"STK"},
{"name":"IUSB","position":"43.00000000","type":"STK"},
{"name":"ETH","position":"0.21860894","type":"CRYPTO"},
{"name":"BTC","position":"0.00505033","type":"CRYPTO"}],
"timestamp":"2024-01-26T12:52:06.946234984"}

### POST schedule reports
POST http://localhost:3000/api/schedule_jobs
Content-Type: application/json

{}
