#!/usr/bin/env bash
# Regenerate the dev-only fund fixture embedded in the
# RestoreDevFundsFixture migration. Run inside the familyfund container,
# or pass --host / --user / -p flags to reach the db container directly.
#
# Example:
#   docker exec -it db bash -c \
#     'cd /tmp && /app/generators/dump_dev_fund_fixtures.sh familyfund_dev'
# or from host:
#   ./dump_dev_fund_fixtures.sh familyfund_dev --host=127.0.0.1 --user=famfun_dev -p1234
set -euo pipefail

db=${1:?"usage: $0 <database> [extra mysqldump args...]"}
shift || true

fund_ids='1080,1081,1082,1083,1084,37529'
account_ids='1833,1834,1835,1836,1837,58944'

out="$(cd "$(dirname "$0")/.." && pwd)/database/migrations/data/restore_dev_funds.sql"
mkdir -p "$(dirname "$out")"

common=(--column-statistics=FALSE --no-create-info --skip-extended-insert
        --skip-add-locks --no-tablespaces --insert-ignore --set-gtid-purged=OFF
        --compact)

# Portfolio IDs belonging to the target funds — captured once so every
# portfolio-scoped table uses the same set.
portfolio_ids=$(mysql "$@" -N -B "$db" -e \
  "SELECT GROUP_CONCAT(id) FROM portfolios WHERE fund_id IN ($fund_ids);")

# Valid asset IDs (portfolio_assets referencing missing asset rows will crash
# the fund show pages). Precomputed so mysqldump's lock doesn't collide with a
# subquery on a separate table.
valid_asset_ids=$(mysql "$@" -N -B "$db" -e "SELECT GROUP_CONCAT(id) FROM assets;")

{
  echo "-- Auto-generated by generators/dump_dev_fund_fixtures.sh"
  echo "-- Restores the hand-curated dev funds that are wiped by a prod data reload."
  echo "-- Regenerate with: app1/family-fund-app/generators/dump_dev_fund_fixtures.sh <db> [conn flags]"
  echo "SET FOREIGN_KEY_CHECKS=0;"

  mysqldump "${common[@]}" "$@" "$db" funds              --where="id IN ($fund_ids)"
  mysqldump "${common[@]}" "$@" "$db" accounts           --where="fund_id IN ($fund_ids)"
  mysqldump "${common[@]}" "$@" "$db" portfolios         --where="fund_id IN ($fund_ids)"
  mysqldump "${common[@]}" "$@" "$db" fund_portfolio     --where="fund_id IN ($fund_ids)"
  # Only include portfolio_assets whose asset row still exists — otherwise
  # rendering blows up on \$pa->asset()->first() returning null.
  mysqldump "${common[@]}" "$@" "$db" portfolio_assets \
    --where="portfolio_id IN ($portfolio_ids) AND asset_id IN ($valid_asset_ids)"
  mysqldump "${common[@]}" "$@" "$db" transactions       --where="account_id IN ($account_ids)"
  mysqldump "${common[@]}" "$@" "$db" account_balances   --where="account_id IN ($account_ids)"
  mysqldump "${common[@]}" "$@" "$db" portfolio_balances --where="portfolio_id IN ($portfolio_ids)"

  echo "SET FOREIGN_KEY_CHECKS=1;"
} > "$out"

echo "Wrote $out ($(wc -l < "$out") lines, $(du -h "$out" | cut -f1))"
